### ISSUE TITLE
Start loop when not connected

### ISSUE THREAD

**Issue by nomadbeni** [atsage/node-red-contrib-LCD20x4-I2C#6]
Hello

Easy to set up, works as expected.
Except if for some reason my raspi restart when the screen is not connected, it goes into a loop, and does not start node-red.
Here is the log.

```
16 Apr 18:31:12 - [info] Started flows
      pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python -u /                                                                                                                                                             home/pi/.node-red/node_modules/node-red-contrib-lcd20x4-i2c/LCD20x4-I2C/lcd20x4_                                                                                                                                                             i2c.py writelcd 20x4 5
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
16 Apr 18:31:13 - [red] Uncaught Exception:
16 Apr 18:31:13 - Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:628:25)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
16 Apr 18:31:32 - [info]
Welcome to Node-RED
===================
16 Apr 18:31:32 - [info] Node-RED version: v0.19.4
```

**Comment by asage-me** [comment]
Sorry, missed this issue somehow.  I've not tested with the screen disconnected.  I'll test and get the error caught.  Thanks for reporting.

**Comment by asage-me** [comment]
@nomadbeni pushed fix to npm
